name: skeletonsplus
description: A Flutter package for building custom skeleton widgets to mimic the page's layout while loading. This package is fork from 'skeletons' package and migrate it to support flutter version 3.22.
version: 0.0.1
homepage: https://github.com/hleanghuor/skeletonsplus

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter: